#!/usr/bin/env node
// @ts-nocheck
import fs from 'node:fs'
import path from 'node:path'
import { assertGate, emitGate, root } from './sks-1-18-gate-lib.js'

const pkg = JSON.parse(fs.readFileSync(path.join(root, 'package.json'), 'utf8'))
const manifest = JSON.parse(fs.readFileSync(path.join(root, 'release-gates.v2.json'), 'utf8'))
const legacy = String(pkg.scripts['release:check:legacy'] || '')
const legacyIds = [...new Set([...legacy.matchAll(/npm run ([^\s&]+)/g)].map((match) => match[1]).filter((id) => pkg.scripts[id]))]
const allowlist = new Map([
  ['release:check:parallel', 'legacy aggregate superseded by release-gates.v2 DAG'],
  ['codex-app:fast-ui-preservation', 'Codex App UI real-environment preservation gate'],
  ['codex-control:keepalive-no-cot-leak', 'long-running remote keepalive/debug gate'],
  ['zellij:real-session-heartbeat', 'real Zellij heartbeat covered by release:real-check'],
  ['publish:packlist-performance', 'publish/package performance gate'],
  ['release:dynamic-performance', 'performance budget gate covered by release:parallel-speed-budget']
])
const gateIds = new Set(manifest.gates.map((gate) => gate.id))
const releasePresetIds = new Set(manifest.gates.filter((gate) => Array.isArray(gate.preset) && gate.preset.includes('release')).map((gate) => gate.id))
const requiredReleasePresetIds = [
  'zellij:first-slot-down-stack',
  'zellij:slot-renderer-proof-semantics',
  'zellij:slot-telemetry',
  'zellij:slot-telemetry-runtime',
  'zellij:slot-pane-telemetry-renderer',
  'zellij:slot-column-anchor-telemetry',
  'agent:slot-telemetry-wiring',
  'zellij:slot-telemetry-renderer',
  'naruto:allocation-policy',
  'naruto:rebalance-policy',
  'naruto:allocation-runtime-wiring',
  'naruto:actual-worker-control-plane',
  'naruto:orchestrator-runtime-source',
  'git:worktree-checkpoint',
  'git:worktree-cross-rebase',
  'local-collab:worktree-gpt-final-apply-policy',
  'release:cache-glob-hashing',
  'release:dag-full-coverage',
  'research:quality-contract',
  'research:claim-matrix',
  'research:source-quality-report',
  'research:implementation-blueprint',
  'research:experiment-plan',
  'research:replication-pack',
  'research:final-reviewer',
  'research:work-graph',
  'research:short-report-rejection',
  'research:complete-package-fixture',
  'research:stage-cycle-runtime-blackbox',
  'research:final-reviewer-blackbox',
  'research:synthesis-writer',
  'research:synthesis-writer-blackbox',
  'research:repetition-detector',
  'research:template-report-rejection',
  'research:real-synthesis-no-deterministic-renderer',
  'research:handoff-consumability',
  'codex-sdk:research-pipeline',
  'release:affected-selector',
  'release:dynamic-presets',
  'release:batch-runner',
  'release:gate-batch-runner',
  'release:aggressive-resource-governor',
  'release:speed-summary',
  'release:speed-summary:check',
  'naruto:ssot-routing',
  'naruto:ssot-route-normalization',
  'naruto:ssot-default',
  'naruto:ssot-gate-aliases',
  'naruto:ssot-pipeline-default',
  'sks:team-alias-to-naruto',
  'team:alias-to-naruto',
  'update:notice',
  'update:gate-removed',
  'update:mad-zellij-notice',
  'mad-db:capability',
  'mad-db:command',
  'mad-db:mad-command',
  'mad-db:priority-resolver',
  'mad-db:ledger',
  'mad-db:one-cycle-consumption',
  'mad-db:safety-conflict-matrix',
  'parallel:runtime-proof',
  'parallel:runtime-proof-events',
  'parallel:runtime-real-blackbox',
  'parallel:claim-enforcement',
  'scheduler:batch-dispatch',
  'scheduler:utilization-proof',
  'native-swarm:process-spawn-proof',
  'native-swarm:zellij-does-not-block-workers',
  'model-call:concurrency',
  'naruto:parallelism-mode',
  'naruto:visible-vs-active-workers',
  'naruto:parallel-runtime-proof',
  'naruto:real-parallelism-blackbox',
  'git:worktree-batch-allocation',
  'release:full-parallelism-blackbox',
  'zellij:slot-telemetry-incremental',
  'zellij:slot-telemetry-performance',
  'team:legacy-create-removed',
  'mad-db:one-cycle-bounded',
  'mad-db:operation-lifecycle-ledger',
  'parallel:strict-pid-proof',
  'parallel:missing-pid-rejection',
  'scheduler:utilization-integral',
  'scheduler:parallel-proof-consistency',
  'zellij:slot-telemetry-live-flush',
  'zellij:slot-pane-stale-detection',
  'mad-db:lifecycle-hook-decision',
  'mad-db:mcp-result-lifecycle',
  'mad-db:operation-lifecycle-blackbox',
  'runtime:proof-summary',
  'runtime:proof-summary-cli',
  'codex:0138-capability',
  'codex:0138-capability-artifact',
  'codex-sdk:version-compat',
  'codex-app:handoff',
  'qa-loop:app-handoff',
  'qa-loop:app-handoff-capability',
  'qa-loop:app-handoff-cli',
  'zellij:qa-app-handoff-status',
  'codex-plugin:json',
  'codex-plugin:inventory',
  'mcp:plugin-inventory',
  'codex-plugin:app-template-policy',
  'image:artifact-path-contract',
  'qa-loop:image-path-exposure',
  'image:generation-path-handoff',
  'image:followup-edit-path',
  'codex:effort-order',
  'qa-loop:effort-escalation',
  'codex:account-usage',
  'qa-loop:budget-policy',
  'naruto:parallel-gate-consistency',
  'codex:0138-doctor',
  'doctor:codex-0138-fix'
]
const missing = legacyIds.filter((id) => !gateIds.has(id) && !allowlist.has(id))
const missingRequiredReleasePreset = requiredReleasePresetIds.filter((id) => !gateIds.has(id) || !releasePresetIds.has(id))
const allowed = legacyIds.filter((id) => allowlist.has(id)).map((id) => ({ id, reason: allowlist.get(id) }))
const coverage = legacyIds.length ? (legacyIds.length - missing.length) / legacyIds.length : 1
const schemaComplete = manifest.gates.every((gate) => gate.id && gate.command && Array.isArray(gate.deps) && Array.isArray(gate.resource) && gate.side_effect && gate.timeout_ms && gate.cache && gate.isolation && Array.isArray(gate.preset))
const report = {
  schema: 'sks.release-dag-full-coverage-check.v1',
  ok: missing.length === 0 && missingRequiredReleasePreset.length === 0 && coverage >= 0.95 && schemaComplete,
  legacy_gate_count: legacyIds.length,
  v2_gate_count: manifest.gates.length,
  coverage,
  missing,
  required_release_preset_ids: requiredReleasePresetIds,
  missing_required_release_preset: missingRequiredReleasePreset,
  allowed,
  schema_complete: schemaComplete
}
assertGate(report.ok, 'release-gates.v2 must cover legacy hermetic release gates', report)
emitGate('release:dag-full-coverage', report)
