export const REQUIRED_4000_RELEASE_IDS = [
  'triwiki:proof-card',
  'triwiki:proof-bank',
  'triwiki:proof-bank-blackbox',
  'triwiki:cache-key',
  'triwiki:module-card',
  'triwiki:gate-impact-map',
  'triwiki:affected-graph',
  'triwiki:affected-graph-blackbox',
  'gate-pack:manifest',
  'gate-pack:runner',
  'gate-pack:runner-blackbox',
  'scheduler:resource-budget',
  'scheduler:extreme-parallel',
  'scheduler:critical-path',
  'pipeline:five-minute-sla',
  'scheduler:extreme-parallel-blackbox',
  'pipeline:five-minute-triwiki-blackbox',
  'build-once:runner',
  'sksd:daemon',
  'sksd:warm-cache-blackbox',
  'probes:memoization',
  'doctor:dirty-plan',
  'doctor:dirty-repair',
  'doctor:dirty-repair-blackbox',
  'legacy:gate-inventory',
  'legacy:gate-purge',
  'orphan:gate-detection',
  'legacy:purge-blackbox',
  'cli:check-tiers',
  'cli:five-minute-task',
  'certificate:sla',
  'sks:400-all-feature-regression'
];

export const REQUIRED_4000_REAL_CHECK_IDS: string[] = [];
