#!/usr/bin/env node
import fs from 'node:fs/promises';
import path from 'node:path';
import { assertGate, emitGate, makeTempRoot, writeText } from './sks-3-1-8-check-lib.js';
import { uninstallCommand } from '../core/commands/uninstall-command.js';

const home = await makeTempRoot('sks-uninstall-home-');
const project = await makeTempRoot('sks-uninstall-project-');
process.env.SKS_UNINSTALL_SKIP_TMP_SWEEP = '1';

await writeText(path.join(home, '.agents', 'skills', 'answer', 'SKILL.md'), '---\nname: answer\ndescription: SKS fixture\n---\n\nSKS managed official fixture.\n');
await writeText(path.join(home, '.agents', 'skills', 'user-global', 'SKILL.md'), '---\nname: user-global\ndescription: User global\n---\n\nUser global skill.\n');
await writeText(path.join(home, '.codex', 'agents', 'lazycodex-executor.toml'), 'name = "lazycodex-executor"\n');
await writeText(path.join(home, '.codex', 'hooks.json'), JSON.stringify({
  UserPromptSubmit: [{ hooks: [{ type: 'command', command: 'sks hook user-prompt-submit' }] }],
  Stop: [{ hooks: [{ type: 'command', command: 'custom-stop' }] }]
}, null, 2));
await writeText(path.join(home, '.codex', 'config.toml'), [
  'default_profile = "sks-fast-high"',
  'service_tier = "fast"',
  '[profiles.sks-fast-high]',
  'model = "gpt-5.5"',
  '[user.fast_mode]',
  'enabled = true',
  '[mcp_servers.user]',
  'url = "https://example.test"'
].join('\n'));
await writeText(path.join(home, '.sneakoscope', 'state.json'), '{}\n');
await writeText(path.join(project, '.agents', 'skills', 'answer', 'SKILL.md'), '---\nname: answer\ndescription: SKS legacy fixture\n---\n\nDollar-command route generated by SKS.\n');
await writeText(path.join(project, '.agents', 'skills', 'forge-one', 'SKILL.md'), '---\nname: forge-one\ndescription: Forge\n---\n\n<!-- BEGIN SKS FORGE SKILL project=x generator=sks@test created=now -->\n');
await writeText(path.join(project, '.agents', 'skills', 'user-one', 'SKILL.md'), '---\nname: user-one\ndescription: User\n---\n\nUser content.\n');

const dry = await uninstallCommand(['--dry-run', '--json', '--home', home]);
assertGate(dry.dry_run === true, 'dry-run must not mutate', dry);
assertGate(dry.inventory.some((item: any) => item.id === 'global-skills' && item.exists === true), 'inventory must include global skills', dry);

const originalCwd = process.cwd();
process.chdir(project);
const applied = await uninstallCommand(['--yes', '--home', home, '--purge-projects', '--keep-data']);
process.chdir(originalCwd);
assertGate(applied.ok === true, 'uninstall apply must pass', applied);
assertGate(!(await exists(path.join(home, '.agents', 'skills', 'answer'))), 'global SKS official skill must be removed');
assertGate(await exists(path.join(home, '.agents', 'skills', 'user-global', 'SKILL.md')), 'global user-authored skill must be preserved');
assertGate(await exists(path.join(home, '.sneakoscope')), '--keep-data must preserve ~/.sneakoscope');
const hooks = JSON.parse(await fs.readFile(path.join(home, '.codex', 'hooks.json'), 'utf8'));
assertGate(JSON.stringify(hooks).includes('custom-stop') && !JSON.stringify(hooks).includes('sks hook'), 'hooks-json must strip SKS entries and preserve user hooks', hooks);
const cfg = await fs.readFile(path.join(home, '.codex', 'config.toml'), 'utf8');
assertGate(cfg.includes('[mcp_servers.user]') && !cfg.includes('sks-fast-high') && !cfg.includes('[user.fast_mode]'), 'config strip must preserve user table and remove SKS-owned fast profile', cfg);
assertGate(!(await exists(path.join(project, '.agents', 'skills', 'answer'))), 'project official residue must be removed');
assertGate(await exists(path.join(project, '.agents', 'skills', 'forge-one', 'SKILL.md')), 'forge skill must be preserved');
assertGate(await exists(path.join(project, '.agents', 'skills', 'user-one', 'SKILL.md')), 'user skill must be preserved');

const second = await uninstallCommand(['--yes', '--home', home, '--keep-config', '--keep-data']);
assertGate(second.ok === true, 'uninstall must be idempotent', second);
emitGate('sks:uninstall-regression', { removed_steps: applied.removed.length, inventory: dry.inventory.length });

async function exists(file: string) {
  return fs.stat(file).then(() => true, () => false);
}
