import path from 'node:path'
import { ensureDir, nowIso, writeTextAtomic } from '../fsx.js'

// Single source of truth for the Zellij clipboard pipeline used by `sks --mad`
// (and any other SKS-launched Zellij session). By default Zellij copies via the
// OSC 52 escape sequence, which several macOS terminals (Terminal.app always,
// some iTerm2 configs) silently drop. Setting copy_command="pbcopy" keeps
// Zellij's copy action wired to the macOS clipboard.
//
// mouse_mode is TRUE on purpose: with mouse_mode off, the trackpad wheel is
// passed straight through to whichever pane has focus (the Codex prompt input),
// so scrolling never reaches the conversation/transcript scrollback the user is
// reading. With mouse_mode on, Zellij captures the wheel and scrolls the pane
// *under the cursor* through its own scrollback — so hovering the conversation
// pane and scrolling moves the transcript, not the prompt. Copy is unaffected:
// copy_on_select + copy_command="pbcopy" make Zellij's own mouse selection copy
// to the system clipboard, and SHIFT+drag still falls back to native terminal
// selection for users who prefer it.

export const ZELLIJ_CLIPBOARD_CONFIG_SCHEMA = 'sks.zellij-clipboard-config.v1'

export interface ZellijClipboardConfig {
  copy_command: string
  copy_clipboard: 'system' | 'primary'
  copy_on_select: boolean
  mouse_mode: boolean
  /** Flags to append to the `zellij ... options` subcommand for the created session. */
  optionFlags: string[]
  /** Path to a dedicated config.kdl for the interactive attach (delivered via ZELLIJ_CONFIG_FILE). */
  config_path: string
  generated_at: string
}

/** Pick the platform-correct clipboard command. macOS is the primary target. */
export function resolveCopyCommand(platform: NodeJS.Platform = process.platform, env: NodeJS.ProcessEnv = process.env): string {
  if (platform === 'darwin') return 'pbcopy'
  // Wayland sessions prefer wl-copy; fall back to xclip on X11. pbcopy is darwin-only.
  if (env.WAYLAND_DISPLAY) return 'wl-copy'
  return 'xclip -selection clipboard'
}

function kdlString(value: string): string {
  return JSON.stringify(String(value || ''))
}

/** Render a minimal, valid Zellij config.kdl that enables clipboard copy. */
export function buildZellijClipboardKdl(cfg: { copy_command: string; copy_clipboard: 'system' | 'primary'; copy_on_select: boolean; mouse_mode: boolean }): string {
  return [
    '// Generated by Sneakoscope (sks) so launched Zellij sessions copy to the OS clipboard.',
    `mouse_mode ${cfg.mouse_mode ? 'true' : 'false'}`,
    `copy_command ${kdlString(cfg.copy_command)}`,
    `copy_clipboard ${kdlString(cfg.copy_clipboard)}`,
    `copy_on_select ${cfg.copy_on_select ? 'true' : 'false'}`,
    ''
  ].join('\n')
}

export async function writeZellijClipboardConfig(
  root: string,
  missionId: string,
  platform: NodeJS.Platform = process.platform
): Promise<ZellijClipboardConfig> {
  const copy_command = resolveCopyCommand(platform)
  const copy_clipboard: 'system' | 'primary' = 'system'
  const copy_on_select = true
  // mouse_mode on: route the trackpad wheel to the pane under the cursor so the
  // conversation/transcript scrolls instead of the focused prompt input. See the
  // module header for the copy interaction (pbcopy + copy_on_select keep Cmd/drag
  // copy working). Opt out with SKS_ZELLIJ_MOUSE_MODE=0 if a terminal misbehaves.
  const mouse_mode = process.env.SKS_ZELLIJ_MOUSE_MODE !== '0'
  const dir = path.join(root, '.sneakoscope', 'missions', missionId)
  await ensureDir(dir)
  const config_path = path.join(dir, 'zellij-clipboard.kdl')
  await writeTextAtomic(config_path, buildZellijClipboardKdl({ copy_command, copy_clipboard, copy_on_select, mouse_mode }))
  return {
    copy_command,
    copy_clipboard,
    copy_on_select,
    mouse_mode,
    // Appended AFTER `--default-layout <path>` in the create command. Zellij treats
    // --copy-command as mutually exclusive with --copy-clipboard (OSC52 target), so
    // only pass the command and copy-on-select flags on the CLI. The generated KDL
    // still records copy_clipboard for config-file consumers that use OSC52.
    optionFlags: ['--copy-command', copy_command, '--copy-on-select', String(copy_on_select), '--mouse-mode', String(mouse_mode)],
    config_path,
    generated_at: nowIso()
  }
}
