import path from 'node:path'
import { ensureDir, nowIso, writeTextAtomic } from '../fsx.js'

// Single source of truth for the Zellij clipboard pipeline used by `sks --mad`
// (and any other SKS-launched Zellij session). By default Zellij copies via the
// OSC 52 escape sequence, which several macOS terminals (Terminal.app always,
// some iTerm2 configs) silently drop — so text selected inside a pane never
// reaches the system clipboard. Setting copy_command="pbcopy" pipes selections
// straight to the macOS clipboard, and copy_on_select=true makes a mouse drag
// copy without entering copy mode. (Shift+drag still falls back to native
// terminal selection regardless.)

export const ZELLIJ_CLIPBOARD_CONFIG_SCHEMA = 'sks.zellij-clipboard-config.v1'

export interface ZellijClipboardConfig {
  copy_command: string
  copy_clipboard: 'system' | 'primary'
  copy_on_select: boolean
  /** Flags to append to the `zellij ... options` subcommand for the created session. */
  optionFlags: string[]
  /** Path to a dedicated config.kdl for the interactive attach (delivered via ZELLIJ_CONFIG_FILE). */
  config_path: string
  generated_at: string
}

/** Pick the platform-correct clipboard command. macOS is the primary target. */
export function resolveCopyCommand(platform: NodeJS.Platform = process.platform, env: NodeJS.ProcessEnv = process.env): string {
  if (platform === 'darwin') return 'pbcopy'
  // Wayland sessions prefer wl-copy; fall back to xclip on X11. pbcopy is darwin-only.
  if (env.WAYLAND_DISPLAY) return 'wl-copy'
  return 'xclip -selection clipboard'
}

function kdlString(value: string): string {
  return JSON.stringify(String(value || ''))
}

/** Render a minimal, valid Zellij config.kdl that enables clipboard copy. */
export function buildZellijClipboardKdl(cfg: { copy_command: string; copy_clipboard: 'system' | 'primary'; copy_on_select: boolean }): string {
  return [
    '// Generated by Sneakoscope (sks) so launched Zellij sessions copy to the OS clipboard.',
    `copy_command ${kdlString(cfg.copy_command)}`,
    `copy_clipboard ${kdlString(cfg.copy_clipboard)}`,
    `copy_on_select ${cfg.copy_on_select ? 'true' : 'false'}`,
    ''
  ].join('\n')
}

export async function writeZellijClipboardConfig(
  root: string,
  missionId: string,
  platform: NodeJS.Platform = process.platform
): Promise<ZellijClipboardConfig> {
  const copy_command = resolveCopyCommand(platform)
  const copy_clipboard: 'system' | 'primary' = 'system'
  const copy_on_select = true
  const dir = path.join(root, '.sneakoscope', 'missions', missionId)
  await ensureDir(dir)
  const config_path = path.join(dir, 'zellij-clipboard.kdl')
  await writeTextAtomic(config_path, buildZellijClipboardKdl({ copy_command, copy_clipboard, copy_on_select }))
  return {
    copy_command,
    copy_clipboard,
    copy_on_select,
    // Appended AFTER `--default-layout <path>` in the create command. The `options`
    // subcommand sets these on the *created* background session; per Zellij CLI docs
    // the value formats are: --copy-on-select true|false, --copy-clipboard system|primary.
    optionFlags: ['--copy-command', copy_command, '--copy-clipboard', copy_clipboard, '--copy-on-select', String(copy_on_select)],
    config_path,
    generated_at: nowIso()
  }
}
