import fs from 'node:fs/promises';
import path from 'node:path';
import { nowIso, writeTextAtomic } from '../../fsx.js';
import { resolveOpenRouterApiKey, openRouterSecretPaths } from '../openrouter/openrouter-secret-store.js';
import type { OpenRouterKeyResolution } from '../openrouter/openrouter-types.js';
import { GLM_52_OPENROUTER_MODEL, type GlmProfileName } from './glm-52-settings.js';
import { resolveGlmProfileFromArgs, type GlmResolvedProfile } from './glm-profile-resolver.js';

export const GLM_MAD_PROFILE_ID = 'sks/glm-5.2-mad' as const;
export const OPENROUTER_CODEX_PROVIDER = 'openrouter' as const;

export interface MadGlmLaunchProfile {
  readonly schema: 'sks.glm-mad-launch-profile.v1';
  readonly profile_name: typeof GLM_MAD_PROFILE_ID;
  readonly provider: typeof OPENROUTER_CODEX_PROVIDER;
  readonly model: typeof GLM_52_OPENROUTER_MODEL;
  readonly glm_profile: GlmProfileName;
  readonly glm_mode: GlmResolvedProfile['mode'];
  readonly launch_args: readonly string[];
  readonly sandbox_mode: 'danger-full-access';
  readonly approval_policy: 'never';
  readonly model_reasoning_effort: 'low' | 'high' | 'xhigh';
  readonly service_tier: 'fast';
  readonly gpt_fallback_allowed: false;
  readonly writes_user_codex_config: false;
}

export interface MadGlmCodexWrapper {
  readonly wrapper_path: string;
  readonly real_codex_bin: string;
  readonly secret_key_path: string;
  readonly raw_key_written_to_wrapper: false;
}

export function buildMadGlmLaunchProfileNoWrite(args: readonly string[] = []): MadGlmLaunchProfile {
  const profile = resolveGlmProfileFromArgs(args);
  const effort = codexReasoningEffortForProfile(profile);
  return {
    schema: 'sks.glm-mad-launch-profile.v1',
    profile_name: GLM_MAD_PROFILE_ID,
    provider: OPENROUTER_CODEX_PROVIDER,
    model: GLM_52_OPENROUTER_MODEL,
    glm_profile: profile.name,
    glm_mode: profile.mode,
    launch_args: [
      '--sandbox',
      'danger-full-access',
      '--ask-for-approval',
      'never',
      '-c',
      'service_tier=fast',
      '-c',
      `model_reasoning_effort=${effort}`,
      '-c',
      'model_provider="openrouter"',
      '-c',
      `model="${GLM_52_OPENROUTER_MODEL}"`,
      '-c',
      'model_providers.openrouter.name="OpenRouter"',
      '-c',
      'model_providers.openrouter.base_url="https://openrouter.ai/api/v1"',
      '-c',
      'model_providers.openrouter.env_key="OPENROUTER_API_KEY"',
      '-c',
      'model_providers.openrouter.wire_api="responses"',
      '-c',
      'model_providers.openrouter.requires_openai_auth=false'
    ],
    sandbox_mode: 'danger-full-access',
    approval_policy: 'never',
    model_reasoning_effort: effort,
    service_tier: 'fast',
    gpt_fallback_allowed: false,
    writes_user_codex_config: false
  };
}

export async function resolveMadGlmLaunchKey(env: NodeJS.ProcessEnv = process.env): Promise<OpenRouterKeyResolution> {
  return resolveOpenRouterApiKey({ env });
}

export async function writeMadGlmCodexWrapper(input: {
  readonly missionDir: string;
  readonly env?: NodeJS.ProcessEnv;
  readonly realCodexBin?: string | null;
}): Promise<MadGlmCodexWrapper> {
  const env = input.env || process.env;
  const paths = openRouterSecretPaths(env);
  const realCodexBin = String(input.realCodexBin || env.SKS_CODEX_BIN || 'codex');
  const wrapperPath = path.join(input.missionDir, 'sks-glm-codex-wrapper.sh');
  await writeTextAtomic(
    wrapperPath,
    buildMadGlmCodexWrapperScript({
      realCodexBin,
      secretKeyPath: paths.keyPath
    })
  );
  await fs.chmod(wrapperPath, 0o700).catch(() => undefined);
  return {
    wrapper_path: wrapperPath,
    real_codex_bin: realCodexBin,
    secret_key_path: paths.keyPath,
    raw_key_written_to_wrapper: false
  };
}

export function buildMadGlmCodexWrapperScript(input: {
  readonly realCodexBin: string;
  readonly secretKeyPath: string;
}): string {
  return [
    '#!/bin/sh',
    'set -eu',
    '# Generated by SKS GLM MAD launch. This wrapper reads the key at runtime',
    '# so Zellij layout artifacts never contain the raw OpenRouter secret.',
    'if [ -z "${OPENROUTER_API_KEY:-}" ] && [ -n "${SKS_OPENROUTER_API_KEY:-}" ]; then',
    '  OPENROUTER_API_KEY="$SKS_OPENROUTER_API_KEY"',
    '  export OPENROUTER_API_KEY',
    'fi',
    `if [ -z "\${OPENROUTER_API_KEY:-}" ] && [ -r ${shellQuote(input.secretKeyPath)} ]; then`,
    `  OPENROUTER_API_KEY="$(cat ${shellQuote(input.secretKeyPath)})"`,
    '  export OPENROUTER_API_KEY',
    'fi',
    'if [ -z "${OPENROUTER_API_KEY:-}" ]; then',
    '  echo "SKS GLM MAD blocked: OPENROUTER_API_KEY is missing. Run sks --mad --glm --repair or export OPENROUTER_API_KEY." >&2',
    '  exit 66',
    'fi',
    `exec ${shellQuote(input.realCodexBin)} "$@"`,
    ''
  ].join('\n');
}

export function buildMadGlmLaunchArtifact(input: {
  readonly missionId: string;
  readonly keyResolution: OpenRouterKeyResolution;
  readonly wrapper: MadGlmCodexWrapper;
  readonly profile?: MadGlmLaunchProfile;
}) {
  const profile = input.profile || buildMadGlmLaunchProfileNoWrite();
  return {
    schema: 'sks.glm-mad-launch.v1',
    generated_at: nowIso(),
    ok: Boolean(input.keyResolution.key),
    mission_id: input.missionId,
    provider: profile.provider,
    model: profile.model,
    glm_profile: profile.glm_profile,
    glm_mode: profile.glm_mode,
    model_reasoning_effort: profile.model_reasoning_effort,
    profile_name: profile.profile_name,
    strict_model_lock: true,
    gpt_fallback_allowed: false,
    openrouter_key_source: input.keyResolution.source || null,
    key_preview: input.keyResolution.key_preview || null,
    wrapper_path: input.wrapper.wrapper_path,
    real_codex_bin: input.wrapper.real_codex_bin,
    raw_key_written_to_wrapper: false,
    codex_args: profile.launch_args,
    blockers: input.keyResolution.key ? [] : input.keyResolution.blockers,
    warnings: input.keyResolution.warnings || []
  };
}

function shellQuote(value: string): string {
  return `'${String(value).replace(/'/g, `'\\''`)}'`;
}

function codexReasoningEffortForProfile(profile: GlmResolvedProfile): 'low' | 'high' | 'xhigh' {
  if (profile.name === 'xhigh') return 'xhigh';
  if (profile.name === 'deep' || profile.name === 'strict') return 'high';
  return 'xhigh';
}
