import { validateAgentWorkerResult } from './agent-worker-pipeline.js'

export async function runFakeAgent(agent: any, slice: any, opts: any = {}) {
  if (Number(slice?.delay_ms || 0) > 0) await delay(Number(slice.delay_ms))
  const patchEnvelopes = buildFixturePatchEnvelopes(agent, slice, opts)
  return validateAgentWorkerResult({
    mission_id: opts.missionId || opts.mission_id || '',
    agent_id: agent.id,
    session_id: agent.session_id,
    persona_id: agent.persona_id || agent.id,
    task_slice_id: slice?.id || '',
    status: 'done',
    backend: 'fake',
    summary: 'Fixture agent ' + agent.id + ' completed ' + (slice?.id || 'slice') + ' for ' + (opts.route || 'agent-run') + '.',
    findings: ['fixture agent completed assigned slice'],
    proposed_changes: [],
    changed_files: [],
    lease_compliance: { ok: true, violations: [] },
    artifacts: ['agent-events.jsonl', 'agent-task-board.json'],
    blockers: [],
    confidence: 'fixture',
    handoff_notes: 'No handoff required for fake backend fixture.',
    unverified: ['fake backend does not prove real parallel execution'],
    writes: [],
    ...(patchEnvelopes.length ? { patch_envelopes: patchEnvelopes } : {}),
    ...(isBugfixSlice(slice) && patchEnvelopes.length ? { regression_proof: fixtureRegressionProof(slice) } : {}),
    ...(isRepairSlice(slice) && patchEnvelopes.length ? { repair_hypothesis: fixtureRepairHypothesis(slice) } : {}),
    ...(slice?.work_item_kind ? { work_item_kind: String(slice.work_item_kind) } : {}),
    ...(slice?.tournament_group_id ? { tournament: fixtureTournament(slice) } : {}),
    source_intelligence_refs: agent.source_intelligence_refs || null,
    goal_mode_ref: agent.goal_mode_ref || null,
    ...(opts.emitFollowUpWorkItems ? { follow_up_work_items: [buildFixtureFollowUp(agent, slice)] } : {}),
    verification: { status: 'fixture', checks: ['schema-normalized-result'] },
    recursion_guard: { ok: true, violations: [] }
  })
}

function delay(ms: number) {
  return new Promise((resolve) => setTimeout(resolve, ms))
}

function buildFixtureFollowUp(agent: any, slice: any) {
  return {
    id: `${String(slice?.id || agent.id)}-follow-up-001`,
    title: 'Fixture follow-up work item',
    description: 'Schema-valid follow-up generated by the fake backend fixture.',
    required_persona_category: 'verifier',
    priority: 100,
    dependencies: [],
    lease_requirements: [],
    max_attempts: 1,
    reason: 'exercise follow_up_work_items scheduler enqueue path',
    source_agent_session_id: agent.session_id
  }
}

export function buildFixturePatchEnvelopes(agent: any, slice: any, opts: any = {}) {
  const writePaths = Array.isArray(slice?.write_paths) ? slice.write_paths.map(String).filter(Boolean) : []
  if (!writePaths.length) return []
  return writePaths.map((file: string, index: number) => {
    const leaseId = `write:${String(agent.id)}:${file}`
    const nodeId = String(slice?.micro_win_id || slice?.id || `patch-${index + 1}`)
    const verificationNodeId = String(slice?.verification_node_id || `verify:${nodeId}`)
    const rollbackNodeId = String(slice?.rollback_node_id || `rollback:${nodeId}`)
    return {
      schema: 'sks.agent-patch-envelope.v1',
      source: 'fixture',
      mission_id: String(opts.missionId || opts.mission_id || ''),
      route: String(opts.route || '$Naruto'),
      agent_id: String(agent.id),
      session_id: String(agent.session_id || ''),
      slot_id: String(agent.slot_id || agent.worker_slot_id || agent.id),
      generation_index: Number(agent.generation_index || 1),
      native_cli_worker_session_id: opts.nativeCliWorkerSessionId || agent.native_cli_worker_session_id || agent.session_id,
      native_cli_process_id: Number(opts.nativeCliProcessId || agent.native_cli_process_id || process.pid),
      worker_process_id: Number(opts.workerProcessId || opts.nativeCliProcessId || agent.native_cli_process_id || process.pid),
      fast_mode: opts.fastMode !== false,
      service_tier: opts.serviceTier === 'standard' ? 'standard' : 'fast',
      task_slice_id: String(slice?.id || ''),
      lease_id: leaseId,
      allowed_paths: [file],
      strategy_task_id: nodeId,
      ...(slice?.micro_win_id ? { micro_win_id: String(slice.micro_win_id) } : {}),
      verification_node_id: verificationNodeId,
      rollback_node_id: rollbackNodeId,
      lease_proof: {
        lease_id: leaseId,
        owner_agent: String(agent.id),
        owner_persona: String(agent.persona_id || agent.role || 'fixture'),
        allowed_paths: [file],
        strategy_task_id: nodeId,
        micro_win_id: slice?.micro_win_id ? String(slice.micro_win_id) : undefined,
        protected_path_check: 'passed',
        conflict_prediction_id: `conflict:${nodeId}`,
        verification_node_id: verificationNodeId,
        rollback_node_id: rollbackNodeId
      },
      operations: [{
        op: 'write',
        path: file,
        content: `patched by ${String(agent.id)} for ${String(slice?.id || 'fixture')}\n`
      }],
      ...(isBugfixSlice(slice) ? { regression_proof: fixtureRegressionProof(slice) } : {}),
      ...(isRepairSlice(slice) ? { repair_hypothesis: fixtureRepairHypothesis(slice) } : {}),
      ...(slice?.tournament_group_id ? { tournament: fixtureTournament(slice) } : {}),
      rationale: 'Fixture patch envelope emitted by fake backend for a leased write task.',
      verification_hint: { node_id: verificationNodeId, expected_status: 'applied_hashes_recorded' },
      rollback_hint: { node_id: rollbackNodeId, strategy: 'restore content_before or delete newly created file' }
    }
  })
}

function isBugfixSlice(slice: any): boolean {
  const text = `${String(slice?.work_item_kind || '')} ${String(slice?.title || '')}`.toLowerCase()
  return /\b(bugfix|fix|bug|regression|broken|failure|crash|error)\b|버그|회귀/.test(text)
}

function isRepairSlice(slice: any): boolean {
  const text = `${String(slice?.work_item_kind || '')} ${String(slice?.title || '')}`.toLowerCase()
  return /\b(conflict_resolution|repair|conflict|rebase|rollback)\b|수리|충돌/.test(text)
}

function fixtureRegressionProof(slice: any) {
  return {
    test_file: String(slice?.target_paths?.[0] || slice?.write_paths?.[0] || 'fixture.test.js'),
    failed_before: true,
    passed_after: true,
    output_digest: 'fixture-regression-proof'
  }
}

function fixtureRepairHypothesis(slice: any) {
  return {
    failure: 'fixture repair target',
    hypotheses: [{ cause: 'fixture conflict', evidence_for: 'simulated failed worker', evidence_against: 'none' }],
    chosen: 'fixture conflict',
    minimal_probe: String(slice?.id || 'fixture')
  }
}

function fixtureTournament(slice: any) {
  return {
    schema: 'sks.solution-tournament-candidate.v1',
    group_id: String(slice.tournament_group_id),
    candidate_index: Number(slice.tournament_candidate_index || 1),
    candidate_count: Number(slice.tournament_candidate_count || 1),
    approach: String(slice.approach_directive || '')
  }
}
