import { validateAgentWorkerResult } from './agent-worker-pipeline.js'

export async function runFakeAgent(agent: any, slice: any, opts: any = {}) {
  if (Number(slice?.delay_ms || 0) > 0) await delay(Number(slice.delay_ms))
  return validateAgentWorkerResult({
    mission_id: opts.missionId || opts.mission_id || '',
    agent_id: agent.id,
    session_id: agent.session_id,
    persona_id: agent.persona_id || agent.id,
    task_slice_id: slice?.id || '',
    status: 'done',
    backend: 'fake',
    summary: 'Fixture agent ' + agent.id + ' completed ' + (slice?.id || 'slice') + ' for ' + (opts.route || 'agent-run') + '.',
    findings: ['fixture agent completed assigned slice'],
    proposed_changes: [],
    changed_files: [],
    lease_compliance: { ok: true, violations: [] },
    artifacts: ['agent-events.jsonl', 'agent-task-board.json'],
    blockers: [],
    confidence: 'fixture',
    handoff_notes: 'No handoff required for fake backend fixture.',
    unverified: ['fake backend does not prove real parallel execution'],
    writes: [],
    source_intelligence_refs: agent.source_intelligence_refs || null,
    goal_mode_ref: agent.goal_mode_ref || null,
    ...(opts.emitFollowUpWorkItems ? { follow_up_work_items: [buildFixtureFollowUp(agent, slice)] } : {}),
    verification: { status: 'fixture', checks: ['schema-normalized-result'] },
    recursion_guard: { ok: true, violations: [] }
  })
}

function delay(ms: number) {
  return new Promise((resolve) => setTimeout(resolve, ms))
}

function buildFixtureFollowUp(agent: any, slice: any) {
  return {
    id: `${String(slice?.id || agent.id)}-follow-up-001`,
    title: 'Fixture follow-up work item',
    description: 'Schema-valid follow-up generated by the fake backend fixture.',
    required_persona_category: 'verifier',
    priority: 100,
    dependencies: [],
    lease_requirements: [],
    max_attempts: 1,
    reason: 'exercise follow_up_work_items scheduler enqueue path',
    source_agent_session_id: agent.session_id
  }
}
