// @ts-nocheck
import path from 'node:path';
import { exists, nowIso, readJson, writeJsonAtomic } from './fsx.js';

export const MANAGED_PATHS_SCHEMA = 'sks.managed-paths.v1';
export const ROLLBACK_SCHEMA = 'sks.rollback.v1';

export function managedPathManifestPath(root) {
  return path.join(root, '.sneakoscope', 'managed-paths.json');
}

export async function managedPathManifest(root) {
  const file = managedPathManifestPath(root);
  const current = await readJson(file, null);
  if (current?.schema === MANAGED_PATHS_SCHEMA) return current;
  const manifest = {
    schema: MANAGED_PATHS_SCHEMA,
    generated_at: nowIso(),
    paths: defaultManagedPaths()
  };
  await writeJsonAtomic(file, manifest);
  return manifest;
}

export function defaultManagedPaths() {
  return [
    row('.sneakoscope', 'runtime state, missions, proof, wiki, evidence, and reports', true),
    row('.codex', 'Codex App hook/config surface generated by SKS setup', true),
    row('.agents/skills', 'Codex App SKS skill surface generated by SKS setup', true),
    row('AGENTS.md', 'repository-level SKS managed instructions block', false)
  ];
}

export async function rollbackList(root) {
  const manifest = await managedPathManifest(root);
  const actions = [];
  for (const entry of manifest.paths.filter((row) => row.rollback)) {
    actions.push({
      id: rollbackId(entry.path),
      path: entry.path,
      exists: await exists(path.join(root, entry.path)),
      action: 'remove-managed-path',
      requires_confirmation: true
    });
  }
  return {
    schema: ROLLBACK_SCHEMA,
    generated_at: nowIso(),
    root,
    actions
  };
}

export function rollbackId(relPath = '') {
  return `rollback-${String(relPath).replace(/[^A-Za-z0-9]+/g, '-').replace(/^-|-$/g, '').toLowerCase() || 'root'}`;
}

function row(relPath, purpose, rollback) {
  return {
    path: relPath,
    owner: 'sks',
    created_by: 'setup',
    purpose,
    rollback: Boolean(rollback)
  };
}
