export const PERMISSION_GATE_SCHEMA_VERSION = 1;

export const MAD_SKS_PERMISSION_PROFILE = Object.freeze({
  schema_version: PERMISSION_GATE_SCHEMA_VERSION,
  id: 'mad_sks_live_full_access',
  command: '$MAD-SKS',
  intent: 'explicit_live_server_intervention',
  scope: 'active_invocation_only',
  authority_surface: 'skill_or_mcp_gate_function',
  allowed: Object.freeze([
    'target_project_file_writes',
    'target_project_config_writes',
    'target_project_shell_commands',
    'target_project_package_manager',
    'package_install_with_allow_package_install',
    'service_control_with_allow_service_control',
    'system_commands_with_allow_system',
    'network_operations_with_allow_network',
    'computer_use_with_allow_computer_use',
    'browser_automation_with_allow_browser_use',
    'generated_asset_edits_with_allow_generated_assets',
    'file_permission_changes_with_allow_file_permissions',
    'live_server_changes',
    'supabase_mcp_database_writes',
    'direct_execute_sql_writes',
    'schema_cleanup',
    'column_cleanup',
    'migration_apply_when_required',
    'normal_dml_with_targeted_scope'
  ]),
  blocked: Object.freeze([
    'drop_database',
    'drop_schema',
    'drop_table',
    'truncate_table',
    'delete_without_where',
    'update_without_where',
    'database_reset',
    'dangerous_project_or_branch_management',
    'credential_exfiltration',
    'persistent_security_weakening',
    'unrequested_fallback_implementation',
    'sks_harness_code_mutation',
    'sks_package_root_mutation',
    'sks_dist_runtime_mutation',
    'sks_release_metadata_mutation',
    'sks_managed_hook_core_mutation'
  ]),
  deactivation: 'mission_gate_passed_or_permissions_deactivated'
});

export function permissionGateSummary(profile: any = MAD_SKS_PERMISSION_PROFILE) {
  return {
    schema_version: PERMISSION_GATE_SCHEMA_VERSION,
    id: profile.id,
    scope: profile.scope,
    authority_surface: profile.authority_surface,
    allowed: [...profile.allowed],
    blocked: [...profile.blocked],
    deactivation: profile.deactivation
  };
}

export function isMadSksRouteState(state: any = {}) {
  return state.mad_sks_active === true
    || String(state.mode || '').toUpperCase() === 'MADSKS'
    || String(state.route_command || '').toUpperCase() === '$MAD-SKS'
    || String(state.route || '').toUpperCase() === 'MADSKS'
    || state.permission_profile?.id === MAD_SKS_PERMISSION_PROFILE.id;
}

export function madSksCatastrophicDbReasons(cls: any = {}) {
  const reasons = new Set([
    ...(cls.reasons || []),
    ...(cls.sql?.reasons || []),
    ...(cls.command?.reasons || [])
  ]);
  const blocked = [
    'drop_database',
    'drop_schema',
    'drop_table',
    'truncate',
    'delete_without_where',
    'update_without_where',
    'supabase_db_reset',
    'prisma_migrate_reset',
    'postgres_database_admin_command'
  ].filter((reason: any) => reasons.has(reason));
  if (cls.toolReasons?.includes?.('dangerous_supabase_management_tool')) blocked.push('dangerous_project_or_branch_management');
  return [...new Set(blocked)];
}

export function madSksCatastrophicSqlLiteralRequirements(cls: any = {}) {
  const reasons = madSksCatastrophicDbReasons(cls);
  const requirements: Record<string, RegExp> = {
    drop_database: /\bdrop\s+database\b/i,
    drop_schema: /\bdrop\s+schema\b/i,
    drop_table: /\bdrop\s+table\b/i,
    truncate: /\btruncate\b/i,
    delete_without_where: /\bdelete\s+from\b(?![\s\S]*\bwhere\b)/i,
    update_without_where: /\bupdate\b[\s\S]*\bset\b(?![\s\S]*\bwhere\b)/i
  };
  return reasons
    .flatMap((reason) => {
      const pattern = requirements[reason];
      return pattern ? [{ reason, pattern }] : [];
    });
}

export function madSksCatastrophicSqlExplicitlyRequested({ classification, userIntent, sql }: any = {}) {
  const requirements = madSksCatastrophicSqlLiteralRequirements(classification || {});
  if (!requirements.length) return { required: false, ok: true, missing: [] as string[] };
  // The SQL text can be generated by the agent. Only the user's literal request
  // or CLI statement counts as explicit catastrophic authorization.
  const haystack = String(userIntent || '');
  const missing = requirements.filter((entry) => !entry.pattern.test(haystack)).map((entry) => entry.reason);
  return {
    required: true,
    ok: missing.length === 0,
    missing
  };
}

export function evaluatePermission({ action, scope, profile, classification, active = false, env = process.env }: any = {}) {
  const selectedProfile = normalizePermissionProfile(profile, env);
  const actionId = String(action || scope || '').trim();
  const blocked = new Set((selectedProfile.blocked || []).map(String));
  const allowed = new Set((selectedProfile.allowed || []).map(String));
  const catastrophic = madSksCatastrophicDbReasons(classification || {});
  const blockedCategories = [
    ...(actionId && blocked.has(actionId) ? [actionId] : []),
    ...catastrophic
  ];
  if (!active) {
    return { matched: false, active: false, allowed: false, action: 'ignore', reasons: ['permission_profile_inactive'], blocked_categories: [], profile: permissionGateSummary(selectedProfile) };
  }
  if (blockedCategories.length) {
    return { matched: true, active: true, allowed: false, action: 'block', reasons: ['permission_profile_blocked_action'], blocked_categories: [...new Set(blockedCategories)], profile: permissionGateSummary(selectedProfile) };
  }
  if (actionId && allowed.size > 0 && !allowed.has(actionId)) {
    return { matched: true, active: true, allowed: false, action: 'block', reasons: ['permission_profile_action_not_allowed'], blocked_categories: [actionId], profile: permissionGateSummary(selectedProfile) };
  }
  return { matched: true, active: true, allowed: true, action: 'allow', reasons: ['permission_profile_scoped_allow'], blocked_categories: [], profile: permissionGateSummary(selectedProfile) };
}

export function evaluateMadSksPermissionGate({ classification, active = false }: any = {}) {
  const cls = classification || { level: 'none', reasons: [] };
  if (!active || !['write', 'destructive'].includes(cls.level)) {
    return { matched: false, active: Boolean(active), allowed: false, action: 'ignore', reasons: [], blocked_categories: [], profile: permissionGateSummary() };
  }
  const decision = evaluatePermission({ action: null, profile: MAD_SKS_PERMISSION_PROFILE, classification: cls, active: true });
  return {
    ...decision,
    reasons: decision.allowed ? ['mad_sks_scoped_live_full_access_active'] : ['mad_sks_catastrophic_db_operation_blocked']
  };
}

function normalizePermissionProfile(profile: any, env: any = process.env) {
  if (profile?.allowed && profile?.blocked) return profile;
  const configured = loadConfiguredPermissionProfiles(env);
  const id = typeof profile === 'string' ? profile : profile?.id;
  return configured.find((row: any) => row.id === id) || MAD_SKS_PERMISSION_PROFILE;
}

function loadConfiguredPermissionProfiles(env: any = process.env) {
  const raw = String(env.SKS_PERMISSION_PROFILES_JSON || '').trim();
  if (!raw) return [];
  try {
    const parsed = JSON.parse(raw);
    return Array.isArray(parsed?.profiles) ? parsed.profiles : Array.isArray(parsed) ? parsed : [];
  } catch {
    return [];
  }
}
