/**
 * Mermaid projection contracts for Architecture Map views (WO §10 / §12).
 */
import {
  MERMAID_PROJECTION_SCHEMA,
  type ArchitectureMapViewId
} from '../../architecture/contracts.js';

export { MERMAID_PROJECTION_SCHEMA };

export type MermaidDirection = 'LR' | 'TD';

export type MermaidSafeId = string & { readonly __mermaidSafeId: unique symbol };

export type ProjectionOmissionReason =
  | 'below_relevance_threshold'
  | 'outside_profile_scope'
  | 'collapsed_into_aggregate'
  | 'duplicate_semantic_edge'
  | 'unsupported_dynamic_relation'
  | 'budget_exhausted_after_protected_set';

export interface ProjectionOmission {
  readonly id: string;
  readonly reason: ProjectionOmissionReason;
  readonly detail?: string;
}

export interface ProjectionAccounting {
  readonly selectedNodeIds: readonly string[];
  readonly emittedNodeIds: readonly string[];
  readonly aggregatedNodeMembers: Readonly<Record<string, readonly string[]>>;
  readonly omittedNodes: readonly ProjectionOmission[];
  readonly selectedEdgeIds: readonly string[];
  readonly emittedEdgeIds: readonly string[];
  readonly aggregatedEdgeMembers: Readonly<Record<string, readonly string[]>>;
  readonly omittedEdges: readonly ProjectionOmission[];
}

export interface MermaidProjectionV1 {
  readonly schema: typeof MERMAID_PROJECTION_SCHEMA;
  readonly viewId: ArchitectureMapViewId;
  readonly direction: MermaidDirection;
  readonly title: string;
  readonly source: string;
  readonly accounting: ProjectionAccounting;
  readonly contentHash: string;
  readonly byteLength: number;
}

export interface MermaidViewSpec {
  readonly viewId: ArchitectureMapViewId;
  readonly title: string;
  readonly direction: MermaidDirection;
  readonly filename: string;
}

export const GENERATED_HEADER =
  '%% GENERATED BY SKS. DO NOT EDIT. SOURCE: TriWiki Context Graph + machine-readable control manifests. %%';

export const MERMAID_TEXT_LIMIT = 50_000;
export const MERMAID_LABEL_DISPLAY_LIMIT = 96;
